### PR TITLE
Replace SDL_CreateRGBSurface by SDL_CreateRGBSurfaceWithFormat

### PR DESCRIPTION
**Pull request by 1bsyl**
Replace SDL_CreateRGBSurface by SDL_CreateRGBSurfaceWithFormat
so that it will be easier to move to SDL3

### CODE REVIEW

**Review by sezero — APPROVED** [review]
This looks OK to me. @slouken?

**Comment by madebr** [comment]
We need to have a SDL2_image branch first.

And for the time being, build+install SDL3 before building SDL3_image on CI (see https://github.com/libsdl-org/SDL/issues/6667).

**Comment by sezero** [comment]
> We need to have a SDL2_image branch first.

This is not an SDL3 patch: This builds against SDL2 just fine.

**Comment by slouken** [comment]
Yup!

**Pull request merged**
