### PR TITLE
Fix PACKAGE_VERSION output in sdl2_image-config-version.cmake

### PR DESCRIPTION
**Pull request by bcarmo-caio**
Currently, when executing `./autogen.sh` and `./configure` we get the following `sdl2_image-config-version.cmake`

```
...
set(PACKAGE_VERSION "@MAJOR_VERSION_MACRO@.@MINOR_VERSION_MACRO@.@MICRO_VERSION_MACRO@")
...
```

This PR fixes this issue using the correct variable names and producing a proper file like

```
...
set(PACKAGE_VERSION "2.6.3")
...
```

### CODE REVIEW

**Review by sezero — APPROVED** [review]

**Comment by sezero** [comment]
I tried to change target branch from `release-2.6.x` to `SDL2` but that
doesn't work. If we do merge this to the release branch, we can cherry pick
to SDL2 branch, though.

P.S.: Curious failure in CI macos runs: any ideas @madebr ?
```
==> Fetching sdl2
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/79823708f871f744e3aa0e6630b6f837c3d2981f/Formula/s/sdl2.rb
==> Cloning https://github.com/libsdl-org/SDL.git
Cloning into '/Users/runner/Library/Caches/Homebrew/sdl2--git'...
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - sdl2.pc.in
Error: Process completed with exit code 1.
```

**Comment by madebr** [comment]
> P.S.: Curious failure in CI macos runs: any ideas @madebr ?

https://github.com/Homebrew/homebrew-core/pull/149190

**Comment by sezero** [comment]
Should we merge this as is to release branch and cherry-pick to SDL2 later?

**Comment by madebr** [comment]
> Should we merge this as is to release branch and cherry-pick to SDL2 later?

That's the normal procedure, but imho the order does not matter much since the change looks trivial (I've not yet tested it).

**Review by madebr — APPROVED** [review]

**Comment by madebr** [comment]
Cherry-picked to SDL2 in 70527e1df877892a0e3e3a1262270cf7236f337c

**Comment by bcarmo-caio** [comment]
Hi there. Thank you for merging the PR so fast and sorry for mistaking the branch names.

I would like to open one more PR. Should I set the base to `SDL2` instead of `release-2.6.x` this time?

Regards

**Comment by sezero** [comment]
> I would like to open one more PR. Should I set the base to `SDL2` instead of `release-2.6.x` this time?

Yes: SDL2-related changes should be against SDL2 branch. If found necessary, they will be applied back to the release branch.

**Comment by madebr** [comment]
In order of preference, depending on what you want to propose and whether it's still present in SDL3:
1. SDL3
2. SD2
3. release-2.6.x

**Comment by bcarmo-caio** [comment]
Great. Thank you for letting me know

**Pull request merged**
