### PR TITLE
CMake updates for SDL3_image

### PR DESCRIPTION
**Pull request by madebr**
- No more 'd' debug suffix
- Use the same so/dylib versioning scheme as used by SDL3
- Install `sdl3-image.pc`
- Add .editorconfig
- Update ci to SDL3 -> fails because SDL3 is not available

Linux prefix:
```
prefix
├── include
│   └── SDL3
│       └── SDL_image.h
├── lib64
│   ├── cmake
│   │   └── SDL3
│   │       ├── Findlibjxl.cmake
│   │       ├── Findwebp.cmake
│   │       ├── SDL3_imageConfig.cmake
│   │       ├── SDL3_imageConfigVersion.cmake
│   │       ├── SDL3_image-shared-targets.cmake
│   │       └── SDL3_image-shared-targets-debug.cmake
│   ├── libSDL3_image.so -> libSDL3_image.so.0
│   ├── libSDL3_image.so.0 -> libSDL3_image.so.0.0.0
│   ├── libSDL3_image.so.0.0.0
│   └── pkgconfig
│       └── sdl3-image.pc
└── share
    └── licenses
        └── SDL3_image
            └── LICENSE.txt
```

MinGW prefix:
```
prefix
├── include
│   └── SDL3
│       └── SDL_image.h
├── lib64
│   ├── cmake
│   │   └── SDL3
│   │       ├── Findlibjxl.cmake
│   │       ├── Findwebp.cmake
│   │       ├── SDL3_imageConfig.cmake
│   │       ├── SDL3_imageConfigVersion.cmake
│   │       ├── SDL3_image-shared-targets.cmake
│   │       └── SDL3_image-shared-targets-debug.cmake
│   ├── libSDL3_image.so -> libSDL3_image.so.0
│   ├── libSDL3_image.so.0 -> libSDL3_image.so.0.0.0
│   ├── libSDL3_image.so.0.0.0
│   └── pkgconfig
│       └── sdl3-image.pc
└── share
    └── licenses
        └── SDL3_image
            └── LICENSE.txt
```

### CODE REVIEW

**Comment by slouken** [comment]
Looks good to me!

**Comment by sezero** [comment]
tga.c and tif.c changes should go in directly, independent of this pull request.

**Comment by sezero** [comment]
> tga.c and tif.c changes should go in directly, independent of this pull request.

... and test/main.c changes too.

**Comment by madebr** [comment]
I think this is good to merge.
`testimage` fails (see https://github.com/libsdl-org/SDL_image/issues/324), but it does too for SDL2_image.

**Comment by slouken** [comment]
Great. Can you make similar changes for SDL_ttf and SDL_mixer?

Thanks!

**Pull request merged**
