### PR TITLE
cmake: Add build options for whether to support saving PNGs

### PR DESCRIPTION
**Pull request by smcv**
Based on code from @madebr.

Resolves: https://github.com/libsdl-org/SDL_image/issues/243

### CODE REVIEW

**Review by madebr — APPROVED** [review]

**Comment by smcv** [comment]
I know @madebr wants to rename all the CMake build options, but in the interests of minimal changes, this PR keeps them consistent with the short names used in `Android.mk`.

**Comment by madebr** [comment]
FYI, the reason I'm renaming the options is to avoid accidental mixing with completely independent projects.
Also, CMake configuration tools such as cmake-gui/ccmake group options by their prefix.

**Comment by smcv** [comment]
> FYI, the reason I'm renaming the options is to avoid accidental mixing with completely independent projects.

Sure, that makes sense, I just don't want to get entangled with larger changes like that one right now.

**Comment by smcv** [comment]
After this and #246 both land, the test glue in #246 can have this change:

```diff
-        # TODO: https://github.com/libsdl-org/SDL_image/issues/243
-        export SDL_IMAGE_TEST_REQUIRE_SAVE_JPG=0
-        export SDL_IMAGE_TEST_REQUIRE_SAVE_PNG=0
+        export SDL_IMAGE_TEST_REQUIRE_SAVE_JPG=1
+        export SDL_IMAGE_TEST_REQUIRE_SAVE_PNG=1
```

**Comment by smcv** [comment]
Obsoleted by #238

**Pull request closed without merging**
