### PR TITLE
IMG_png.c: remove volatile keywords handle longjmp issues better

### PR DESCRIPTION
**Pull request by sezero**
Reference issue: https://github.com/libsdl-org/SDL_image/issues/416

### CODE REVIEW

**Review by slouken — APPROVED** [review]
This looks good to me!

**Comment by sezero** [comment]
@smcv: Can you see any gotchas here? If this is foolproof, I'd like to backport to SDL2 too.  (And maybe some testcases that should hit longjmp and XFAIL?)

**Review by 1bsyl — COMMENTED** [review]
seems ok to me !

**Comment by sezero** [comment]
Got two approvals, therefore merging.

Please open a new ticket for any further fixes and/or improvements.

**Comment by sezero** [comment]
Now backported to SDL2 branch, too.

**Pull request merged**
