### PR TITLE
stb_image.h: upgrade to newest mainstream version

### PR DESCRIPTION
**Pull request by sezero**
This upgrades stb_image.h to newest mainstream version and applies
some fuzz fixes from mainstream pull requests: There are a lot of fixes
applied to the library and ours was left quite behind.

CC: @flibitijibibo as the original author submitted the stb_image support.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Will check this out on Monday, but: I ran into the exact same thing with thread locals, wasn't sure if there was an easy way to get SDL_TLS involved:

https://github.com/FNA-XNA/FNA3D/blob/master/src/FNA3D_Image.c#L152

Fixing that would be nice to have for MinGW in particular, where enabling it drags in added runtime dependencies.

**Comment by sezero** [comment]
OK, waiting for your review.

And yes, it'd be really good to port thread-local stuff to SDL_TLS.

**Comment by sezero** [comment]
Actually, our use of stb_image requires tls support only for error messages??
With some evil ifdefs & co, can it not be set to use SDL_error interface directly?
(unless I'm missing something, of course.)

**Comment by flibitijibibo** [comment]
Just looked and you're right... it's just errors and a flipping feature that never gets used (but also can't be def'd out easily, so it'd just be dead code). So yeah, maybe we can map it to error functions somehow.

**Comment by sezero** [comment]
BTW, there are a lot of dead code, which emits unused warnings.
I don't have a pure & clean way to silence:
```
stb_image.h:1458: warning: 'stbi_load_from_memory' defined but not used
stb_image.h:1444: warning: 'stbi_load_16_from_memory' defined but not used
stb_image.h:1451: warning: 'stbi_load_16_from_callbacks' defined but not used
stb_image.h:1588: warning: 'stbi_is_hdr_from_callbacks' defined but not used
stb_image.h:1546: warning: 'stbi_is_hdr_from_memory' defined but not used
stb_image.h:7727: warning: 'stbi_info_from_memory' defined but not used
stb_image.h:7734: warning: 'stbi_info_from_callbacks' defined but not used
stb_image.h:7741: warning: 'stbi_is_16_bit_from_memory' defined but not used
stb_image.h:7748: warning: 'stbi_is_16_bit_from_callbacks' defined but not used
stb_image.h:5011: warning: 'stbi_set_unpremultiply_on_load' defined but not used
stb_image.h:5016: warning: 'stbi_convert_iphone_png_to_rgb' defined but not used
stb_image.h:1145: warning: 'stbi_set_flip_vertically_on_load' defined but not used
stb_image.h:5028: warning: 'stbi_set_unpremultiply_on_load_thread' defined but not used
stb_image.h:5034: warning: 'stbi_convert_iphone_png_to_rgb_thread' defined but not used
stb_image.h:1155: warning: 'stbi_set_flip_vertically_on_load_thread' defined but not used
stb_image.h:4528: warning: 'stbi_zlib_decode_malloc' defined but not used
stb_image.h:4549: warning: 'stbi_zlib_decode_buffer' defined but not used
stb_image.h:4560: warning: 'stbi_zlib_decode_noheader_malloc' defined but not used
stb_image.h:4576: warning: 'stbi_zlib_decode_noheader_buffer' defined but not used
```

**Comment by sezero** [comment]
> Just looked and you're right... it's just errors and a flipping feature that never gets used (but also can't be def'd out easily, so it'd just be dead code). So yeah, maybe we can map it to error functions somehow.

Is the following good?
```diff
diff --git a/IMG_stb.c b/IMG_stb.c
index c166ed8..dc6247f 100644
--- a/IMG_stb.c
+++ b/IMG_stb.c
@@ -41,12 +41,14 @@
 #define strtol SDL_strtol
 
 #define pow SDL_pow
 #define ldexp SDL_scalbn
 
 #define STB_IMAGE_STATIC
+#define STBI_NO_THREAD_LOCALS
+#define STBI_FAILURE_USERMSG
 #define STBI_NO_STDIO
 #define STBI_ONLY_PNG
 #define STBI_ONLY_JPEG
 #define STBI_NO_GIF
 #define STBI_NO_HDR
 #define STBI_NO_LINEAR
@@ -106,13 +108,12 @@ SDL_Surface *IMG_LoadSTB_RW(SDL_RWops *src)
         &h,
         &format,
         STBI_default
     );
     if ( !pixels ) {
         SDL_RWseek(src, start, RW_SEEK_SET);
-        IMG_SetError("%s", stbi_failure_reason());
         return NULL;
     }
 
     /* Determine the surface format */
     SDL_assert(format == STBI_rgb || format == STBI_rgb_alpha);
 #if SDL_BYTEORDER == SDL_BIG_ENDIAN
diff --git a/stb_image.h b/stb_image.h
index 8422a97..89cfa7e 100644
--- a/stb_image.h
+++ b/stb_image.h
@@ -482,15 +482,17 @@ STBIDEF int    stbi_is_hdr_from_memory(stbi_uc const *buffer, int len);
 #ifndef STBI_NO_STDIO
 STBIDEF int      stbi_is_hdr          (char const *filename);
 STBIDEF int      stbi_is_hdr_from_file(FILE *f);
 #endif // STBI_NO_STDIO
 
 
+#if 0 /* SDL_image change */
 // get a VERY brief reason for failure
 // on most compilers (and ALL modern mainstream compilers) this is threadsafe
 STBIDEF const char *stbi_failure_reason  (void);
+#endif /**/
 
 // free the loaded image -- this is just free()
 STBIDEF void     stbi_image_free      (void *retval_from_stbi_load);
 
 // get image dimensions & components without fully decoding
 STBIDEF int      stbi_info_from_memory(stbi_uc const *buffer, int len, int *x, int *y, int *comp);
@@ -989,29 +991,37 @@ static int      stbi__gif_info(stbi__context *s, int *x, int *y, int *comp);
 static int      stbi__pnm_test(stbi__context *s);
 static void    *stbi__pnm_load(stbi__context *s, int *x, int *y, int *comp, int req_comp, stbi__result_info *ri);
 static int      stbi__pnm_info(stbi__context *s, int *x, int *y, int *comp);
 static int      stbi__pnm_is16(stbi__context *s);
 #endif
 
+#ifndef STBI_NO_FAILURE_STRINGS
+#if 1 /* SDL_image change: */
+static int stbi__err(const char *str)
+{
+   IMG_SetError("%s", str);
+   return 0;
+}
+#else /* SDL_image change. */
 static
 #ifdef STBI_THREAD_LOCAL
 STBI_THREAD_LOCAL
 #endif
 const char *stbi__g_failure_reason;
 
 STBIDEF const char *stbi_failure_reason(void)
 {
    return stbi__g_failure_reason;
 }
 
-#ifndef STBI_NO_FAILURE_STRINGS
 static int stbi__err(const char *str)
 {
    stbi__g_failure_reason = str;
    return 0;
 }
+#endif /**/
 #endif
 
 static void *stbi__malloc(size_t size)
 {
     return STBI_MALLOC(size);
 }
```

**Comment by slouken** [comment]
Yep, looks fine to me.

**Comment by sezero** [comment]
> Yep, looks fine to me.

Pushed to the branch in this PR.

Awaiting reviews.

**Comment by sezero** [comment]
> BTW, there are a lot of dead code, which emits unused warnings. I don't have a pure & clean way to silence:
> 
> ```
> stb_image.h:1458: warning: 'stbi_load_from_memory' defined but not used
> stb_image.h:1444: warning: 'stbi_load_16_from_memory' defined but not used
> stb_image.h:1451: warning: 'stbi_load_16_from_callbacks' defined but not used
> stb_image.h:1588: warning: 'stbi_is_hdr_from_callbacks' defined but not used
> stb_image.h:1546: warning: 'stbi_is_hdr_from_memory' defined but not used
> stb_image.h:7727: warning: 'stbi_info_from_memory' defined but not used
> stb_image.h:7734: warning: 'stbi_info_from_callbacks' defined but not used
> stb_image.h:7741: warning: 'stbi_is_16_bit_from_memory' defined but not used
> stb_image.h:7748: warning: 'stbi_is_16_bit_from_callbacks' defined but not used
> stb_image.h:5011: warning: 'stbi_set_unpremultiply_on_load' defined but not used
> stb_image.h:5016: warning: 'stbi_convert_iphone_png_to_rgb' defined but not used
> stb_image.h:1145: warning: 'stbi_set_flip_vertically_on_load' defined but not used
> stb_image.h:5028: warning: 'stbi_set_unpremultiply_on_load_thread' defined but not used
> stb_image.h:5034: warning: 'stbi_convert_iphone_png_to_rgb_thread' defined but not used
> stb_image.h:1155: warning: 'stbi_set_flip_vertically_on_load_thread' defined but not used
> stb_image.h:4528: warning: 'stbi_zlib_decode_malloc' defined but not used
> stb_image.h:4549: warning: 'stbi_zlib_decode_buffer' defined but not used
> stb_image.h:4560: warning: 'stbi_zlib_decode_noheader_malloc' defined but not used
> stb_image.h:4576: warning: 'stbi_zlib_decode_noheader_buffer' defined but not used
> ```

Pushed https://github.com/libsdl-org/SDL_image/commit/090ce0835d8396fd3cc9b2324e6d8dd4763e0b9a for it for the time being. Not pretty, but does its job.

**Pull request merged**
